### PR TITLE
Pulling edchiefcomplaint members from HDRUK V2 Google sheet

### PR DESCRIPTION
**Pull request by MattStammers**
https://docs.google.com/spreadsheets/d/18XbVmWJsccACoTDFd8EBeslKPtsPApqi/edit#gid=589962562

### CODE REVIEW

**Comment by vvcb** [comment]
Thanks @MattStammers . 

I think #36 that @ccarenzoIC raised is subtly different and is around the feature engineering aspect. 

Moreover, it will also break the current workflow around how missing or erroneous codes that are not in a refset are labelled.

Please see [`feature_maps.py`](https://github.com/LTHTR-DST/hdruk_avoidable_admissions/blob/dev/avoidable_admissions/features/feature_maps.py#L159-L197) for how this is achieved through a combination of the `{category:[array of codes]}` dictionaries that appear later in the same module and the refset members data that appears in [`nhsdd_snomed.py`](https://github.com/LTHTR-DST/hdruk_avoidable_admissions/blob/dev/avoidable_admissions/data/nhsdd_snomed.py). 

`nhsdd_snomed.py` is meant to be autogenerated using [`nhsdd_generator.py`](https://github.com/LTHTR-DST/hdruk_avoidable_admissions/blob/dev/avoidable_admissions/utils/nhsdd_generator.py).

Happy to jump on a quick call this afternoon if it will help.

**Comment by MattStammers** [comment]
Don't merge it if it will break the rest of the workflow. If @ccarenzoIC is also working on this then prioritize what she is doing as she has been working on this for far longer than I have (just tinkering with it this morning)

**Comment by ccarenzoIC** [comment]
Yes, mine as @vvcb if for the feature engineering part. I will work on this during the week.

Thanks,

**Comment by ccarenzoIC** [comment]
On my side, will push the feature engineering code for grouping the chief complaint (https://github.com/LTHTR-DST/hdruk_avoidable_admissions/issues/36)  tomorrow morning and let you know if I'm facing any problem. Apologies, got delayed with other projects

**Comment by ccarenzoIC** [comment]
> On my side, will push the feature engineering code for grouping the chief complaint (#36) tomorrow morning and let you know if I'm facing any problem. Apologies, got delayed with other projects

https://github.com/LTHTR-DST/hdruk_avoidable_admissions/pull/40

**Pull request closed without merging**
